version: '3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:13.0
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: mkostya/foodgram_backend
    env_file:
      - .env
    volumes:
      - static:/app/static_django/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: mkostya/foodgram_frontend
    volumes:
      - static_frontend:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_frontend:/static_frontend/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/var/html/media/
      - static:/app/static_django/
